task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-11-4
  install_script: pkg install -y meson pkgconf libfmt libyaml googletest python3 py38-cython py38-pytest py38-pytest-timeout
  script: |
    set -e
    meson build
    ninja -vC build
    cd python
    python3 setup.py build_ext --inplace --library-dirs=../build/src --rpath=`pwd`/../build/src

  test_script: |
    set -e
    meson test --no-suite slow -C build --no-rebuild --print-errorlogs
    cd python
    python3 -m pytest --log-level=DEBUG --timeout 60 -v || true # Not all tests are passing on FreeBSD now
