#!/usr/bin/env python3
# vim: sts=4 sw=4 et

import argparse
import importlib.resources
import logging
import os
import pathlib
import shutil
import sys
import tempfile

from mako.lookup import TemplateLookup

from tll import logger
import tll.scheme as S

if not hasattr(importlib.resources, 'files'):
    import pkg_resources
    importlib.resources.files = lambda m: pkg_resources.resource_filename(*m.split('.', 1))

def safe_write(filename, data):
    p = pathlib.Path(filename)
    if not p.parent.exists():
        p.parent.mkdir(parents=True)
    dest, name = tempfile.mkstemp(dir=p.parent, prefix=p.name)

    try:
        os.write(dest, data)
        os.close(dest)
        shutil.move(name, p)
    except:
        os.unlink(name)
        raise

parser = argparse.ArgumentParser(description='Generate source code from scheme')
parser.add_argument('scheme', metavar='SCHEME', type=str,
                    help='scheme file')
parser.add_argument('--help-template', dest='help_template', action='store_true',
                    default=False,
                    help='show template help message')
parser.add_argument('-f', '--format', dest='format', type=str,
                    default='cpp', metavar='[PATH/]FORMAT',
                    help='template to use, with optional path to file before / symbol')
parser.add_argument('-o', '--output', dest='output', type=str,
                    help='output file, defaults to stdout')
parser.add_argument('-T', '--template-dir', dest='template_dir', action='append',
                    default=[],
                    help='additional template directories')
parser.add_argument('-l', '--loglevel', dest='loglevel', default='warning',
                    help='logging level', choices=['trace', 'debug', 'info', 'warning', 'error', 'critical'])

def parsepair(string):
    r = string.split('=', 1)
    if len(r) != 2:
        raise ValueError("Invalid key=value pair")
    return r

channels = parser.add_argument_group('Channel options')
channels.add_argument('-c', '--channel', dest='channel', action='store_true',
                    default=False,
                    help='treat SCHEME as channel and load scheme from it')
channels.add_argument('--control', dest='control', action='store_true',
                    default=False,
                    help='load scheme of control messages')
channels.add_argument('--no-open', dest='no_open', action='store_true',
                    help='do not try to open channel')
channels.add_argument('-m', '--module', dest='modules', action='append',
                    default=[],
                    help='additional channel modules')
channels.add_argument('--master', dest='master',
                    help='master channel')
channels.add_argument('--timeout', dest='timeout', type=float,
                    default=1,
                    help='open timeout for channel')
channels.add_argument('--resolve', dest='resolve', type=str,
                    help='address of resolve service')
channels.add_argument('--open', dest='open', metavar='KEY=VALUE',
                    help='open parameters, can be specified multiple times', action='append', default=[], type=parsepair)

args, rest = parser.parse_known_args()

dirs = args.template_dir + [importlib.resources.files('tll.templates'), '/usr/share/tll/templates']
if '/' in args.format:
    path, args.format = args.format.rsplit('/', 1)
    dirs += [path]

lookup = TemplateLookup(
        dirs,
        input_encoding='utf-8',
        output_encoding='utf-8',
        )
tmpl = lookup.get_template(args.format + '.mako')

subparser = argparse.ArgumentParser(description=f'Extra arguments for {args.format} template')
if tmpl.has_def('setup_options'):
    tmpl.get_def('setup_options').render(subparser)

if args.help_template:
    subparser.print_help()
    sys.exit(0)

options = subparser.parse_args(rest)

logger.init()
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(levelname)-7s %(name)s: %(message)s')
logger.configure({'levels.*': args.loglevel})

if args.channel:
    from tll.channel import Context
    from tll.config import Config
    from tll.processor import Loop
    import time

    timeout = time.time() + args.timeout
    defaults = Config()
    if args.resolve:
        proto = 'tcp://' if '://' not in args.resolve else ''
        defaults['resolve.request'] = f'{proto}{args.resolve}'
    ctx = Context(defaults)
    for m in args.modules:
        ctx.load(m)
    master = ctx.Channel(args.master) if args.master else None
    c = ctx.Channel(args.scheme, master=master)
    if not args.no_open:
        if master:
            master.open()
        cfg = Config()
        for k,v in args.open:
            cfg[k] = v
        c.open(cfg)
        if c.state != c.State.Active:
            loop = Loop()
            if master:
                loop.add(master)
            loop.add(c)
            while c.state == c.State.Opening:
                if timeout < time.time():
                    print("Timeout waiting for channel")
                    sys.exit(1)
                loop.step(1)
    scheme = c.scheme_control if args.control else c.scheme
    if not scheme:
        raise SystemExit(f"Channel '{args.scheme}' has no {'control' if args.control else 'data'} scheme")
    c.close()
    del c
else:
    url = args.scheme
    if '://' not in url:
        url = 'yaml://' + url
    scheme = S.Scheme(url)
data = tmpl.render(S = S, scheme=scheme, options=options)

if args.output in (None, '-'):
    sys.stdout.buffer.write(data)
else:
    safe_write(args.output, data)
